version: '3.7'
services:
  server:
    container_name: fast-api-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    ports:
      - "8080:80"
    environment:
      - DEV='True'

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-volume: